export const en = {
      "home.title": "Welcome to Age Of Empire DEfitive Edition statistic viewer",
      "home.projectExplain": "This project is under dev !  Age of Empires II: Definitive Edition — Update 36202",
      "home.warning": "We are in dev, this is a Alpha !",
      "menu.home": "HOME",
      "menu.units": "UNITS",
      "menu.categories": "CATEGORIES",
      "menu.options": "OPTIONS",
      "home.unitProgression.title" : "% of units",
      "home.civProgression.title" : "% of civilizations",
      "home.techProgression.title" : "% of technologies",
      "unit.404" : "no unit with id {idUnit}",
      "goHome" : "Back to home",
      "unit.stat.label" : "General characteristics",
      "unit.stat.hitpoint" : "Hit Points",
      "unit.stat.speed" : "Move speed",
      "unit.stat.lineSigth" : "Line of Sigth",
      "unit.stat.range" : "Range",
      "unit.stat.attack.damageMelee" : "Melee Dammage",
      "unit.stat.attack.damagePierce" : "Piercing Dammage",
      "unit.stat.defense.melee" : "Def. Melee",
      "unit.stat.defense.pierce" : "Def. Pierce",
      "option.lang.confirm":"you'r favorite language has been set to {lang}",
      "option.resetalldata":" LocalStorage has been clean",
 }
  
